### ISSUE TITLE
Interface duplicates after fullscreen mode on Ubuntu 16.04

### ISSUE THREAD

**Issue by adarrra** [oferkv/phototonic#215]
Hi!
First of all I want to say that app is awesome, the best from what I use on Ubuntu. Nice, clean and functional UI.

I have such bug: after escaping fullscreen mode interface "duplicates".  The "layer" under became not clickable.  After resize - everything normalize. 

![photonic_bug](https://cloud.githubusercontent.com/assets/8931638/18847931/c90a49e2-8434-11e6-83b1-bd1962f178a8.png)

**Comment by mnwstl** [comment]
I have the same problem in ubuntu 10.16

**Comment by m-sundman** [comment]
In which release is this supposed to be fixed? This problem still exists in v2.1, which was released way after the fix was committed.

**Comment by mnwstl** [comment]
I currently use Ubuntu 18.04 and Phototonic v 2.0. The application no longer presents the problem cited above.

**Comment by m-sundman** [comment]
mnwstl, I also thought it was fixed in v2.0, but it's there in v2.1, also on (k)ubuntu 18.04, from the repo `deb http://ppa.launchpad.net/dhor/myway/ubuntu bionic main`

**Comment by mnwstl** [comment]
I upgraded to 2.1. I see that a revision is needed for the translation of the Portuguese language. I'll update and upload the files.

**Comment by oferkv** [comment]
@m-sundman Thanks for the input.
What are the step by step reproduction instructions for this issue?
Thanks!

**Comment by mnwstl** [comment]
Hello! I installed version 2.1 and the problem came back.

When I start the phototonic, it works normal:
![pht01](https://user-images.githubusercontent.com/22776404/38461534-9786db88-3aa9-11e8-811e-fff15fd4c35f.jpg)

When I preview a photo, it also works normal:
![pht02](https://user-images.githubusercontent.com/22776404/38461535-97cc5fa0-3aa9-11e8-83c3-7c60da391321.jpg)

But when I close the view, the problem occurs:
![pht03](https://user-images.githubusercontent.com/22776404/38461536-97edf264-3aa9-11e8-812c-b0b53582e3f3.jpg)

To normalize I have to restore and then maximize the window. I had to go back to 2.0.
